CREATE TABLE if not exists PRODUCT(
PROD_ID INT auto_increment,
PROD_NAME VARCHAR(20) NOT NULL DEFAULT "DUMMY",
PROD_DESC VARCHAR(60),
CAT_ID INT NOT NULL,
primary key(PROD_ID),
FOREIGN KEY(CAT_ID) REFERENCES CATEGORY(CAT_ID));