/*Creating database E-Commerce*/
Create database ECommerceDBMS;
use ECommerceDBMS;
Create table supplier(
SUPP_ID INT PRIMARY KEY,
SUPP_NAME VARCHAR(50) NOT NULL,
SUPP_CITY VARCHAR(50) NOT NULL,
SUPP_PHONE VARCHAR(50) NOT NULL);
Create table customer(
CUS_ID INT PRIMARY KEY,
CUS_NAME VARCHAR(20) NOT NULL,
CUS_PHONE VARCHAR(10) NOT NULL,
CUS_CITY VARCHAR(30) NOT NULL,
CUS_GENDER CHAR);
CREATE TABLE CATEGORY(
CAT_ID INT PRIMARY KEY,
CAT_NAME VARCHAR(20) NOT NULL);
CREATE TABLE PRODUCT(
PROD_ID INT PRIMARY KEY,
PROD_NAME VARCHAR(20) NOT NULL DEFAULT "DUMMY",
PROD_DESC VARCHAR(60),
CAT_ID INT NOT NULL,
FOREIGN KEY(CAT_ID) REFERENCES CATEGORY(CAT_ID));
CREATE TABLE SUPPLIER_PRICING(
PRICING_ID INT PRIMARY KEY,
PROD_ID INT NOT NULL,
foreign key(PROD_ID) REFERENCES PRODUCT(PROD_ID),
SUPP_ID INT NOT NULL,
foreign key(SUPP_ID) references SUPPLIER(SUPP_ID),
SUPP_PRICE INT default 0);
CREATE TABLE order_details(
ORD_ID INT PRIMARY KEY,
ORD_AMOUNT INT NOT NULL,
ORD_DATE DATE NOT NULL,
CUS_ID INT NOT NULL,
FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID),
PRICING_ID INT NOT NULL,
FOREIGN KEY(PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID));
CREATE table RATING(
RAT_ID INT PRIMARY KEY,
ORD_ID INT NOT NULL,
FOREIGN KEY(ORD_ID) REFERENCES ORDER_DETAILS(ORD_ID),
RAT_RATSTARS INT NOT NULL);